version: "3.9"
services:
  kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1.19.6
    ports:
      - "3001:3001"
    restart: always
    volumes:
      - uptime-kuma:/app/data
  api:
    build: .
    # image: medaziz11/uptimekuma_restapi:1.2
    volumes:
      - api:/db
    restart: always
    environment:
      - KUMA_SERVER=http://172.31.49.227:3001
      - KUMA_USERNAME=admin
      - KUMA_PASSWORD=admin123#
      - ADMIN_PASSWORD=admin
      # - ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION:-1}
      - SECRET_KEY=${SECRET_KEY:-pO8WunLtrznm2i4NfOJ25BkG4sh4kYwN1FjzZp8O6E0} #random 32bit string that's url safe.
    ports:
      - "8000:8000"

volumes:
  uptime-kuma:
  api:
